In [18]:
import pandas as pd
df1 = pd.read_csv('혼밥식당_크롤링_0_to_737.csv')
df2 = pd.read_csv('혼밥식당_크롤링_737_to_1473.csv')
df3 = pd.read_csv('혼밥식당_크롤링_1474_to_2210.csv')
df4 = pd.read_excel('혼밥식당_크롤링_2210_to_end.xlsx')
df_dobong =

In [19]:
df2 = df2.loc[:,'지역명':]
df3 = df3.loc[:,'지역명':]
df4 = df4.loc[:,'지역명':]

In [20]:
df = pd.concat([df1, df2,df3,df4]).reset_index(drop=True)

In [21]:
# 정보없음 떨구기
df = df[(df['평점'] != '정보 없음') & (df['방문자 리뷰 수'] != '정보 없음') & (df['블로그 리뷰 수'] != '정보 없음')].reset_index(drop=True)
# 세종시 떨구기
df = df[~df['지역명'].str.contains('세종특별자치시')].reset_index(drop=True)

In [22]:
# 문자형 -> 수치형 변수 전환
df['평점'] = df['평점'].apply(lambda x: x.replace('별점\n',''))
df['방문자 리뷰 수'] = df['방문자 리뷰 수'].apply(lambda x: x.replace('방문자 리뷰',''))
df['방문자 리뷰 수'] = df['방문자 리뷰 수'].apply(lambda x: x.replace(',',''))

df['블로그 리뷰 수'] = df['블로그 리뷰 수'].apply(lambda x: x.replace('블로그 리뷰',''))
df['블로그 리뷰 수'] = df['블로그 리뷰 수'].apply(lambda x: x.replace(',',''))

df['평점'] = df['평점'].astype('float64') 
df['방문자 리뷰 수'] = df['방문자 리뷰 수'].astype('int64') 
df['블로그 리뷰 수'] = df['블로그 리뷰 수'].astype('int64')

df

,지역명,가게 이름,카테고리,평점,방문자 리뷰 수,블로그 리뷰 수,주소,전화번호
0,서울특별시 종로구 청운효자동,청담동 마녀김밥 광화문점,김밥,4.36,4860,210,서울 종로구 새문안로 105,0507-1458-1146
1,서울특별시 종로구 청운효자동,KFC 광화문점,햄버거,4.30,6134,103,서울 종로구 세종대로23길 7,02-738-9870
2,서울특별시 종로구 청운효자동,진심,일식당,4.58,1253,1010,서울 종로구 필운대로 42-1 1층,070-7789-5820
3,서울특별시 종로구 청운효자동,밥+,한식,4.42,547,438,서울 종로구 옥인길 9,0507-1391-1293
4,서울특별시 종로구 청운효자동,공기식당,카레,4.48,561,673,서울 종로구 필운대로6길 20-1 1층,0507-1440-0930
...,...,...,...,...,...,...,...,...
14727,전북특별자치도 부안군 백산면,장수해장국,해장국,4.38,219,19,전북 부안군 부안읍 송정길 13 장수해장국,NaN
14728,전북특별자치도 부안군 백산면,최고다김밥 본점,김밥,4.41,199,11,전북 부안군 부안읍 봉신길 9,NaN
14729,전북특별자치도 부안군 백산면,롯데리아 부안점,햄버거,4.13,827,14,전북 부안군 부안읍 석정로 191,NaN
14730,전북특별자치도 부안군 백산면,형제골뼈다귀순대국,감자탕,4.27,1290,138,전북 부안군 부안읍 용암로 32,NaN
14731,전북특별자치도 부안군 상서면,개암곰탕,"곰탕,설렁탕",4.33,650,42,전북 부안군 상서면 부안로 1567,NaN

In [23]:
#df.to_csv('혼밥가능식당_시각화용.csv',index=False)

In [24]:
df['시도명'] =  df['지역명'].apply(lambda x: x.split(' ')[0])
df['시군구'] = df['지역명'].apply(lambda x: x.split(' ')[1])
df

,지역명,가게 이름,카테고리,평점,방문자 리뷰 수,블로그 리뷰 수,주소,전화번호,시도명,시군구
0,서울특별시 종로구 청운효자동,청담동 마녀김밥 광화문점,김밥,4.36,4860,210,서울 종로구 새문안로 105,0507-1458-1146,서울특별시,종로구
1,서울특별시 종로구 청운효자동,KFC 광화문점,햄버거,4.30,6134,103,서울 종로구 세종대로23길 7,02-738-9870,서울특별시,종로구
2,서울특별시 종로구 청운효자동,진심,일식당,4.58,1253,1010,서울 종로구 필운대로 42-1 1층,070-7789-5820,서울특별시,종로구
3,서울특별시 종로구 청운효자동,밥+,한식,4.42,547,438,서울 종로구 옥인길 9,0507-1391-1293,서울특별시,종로구
4,서울특별시 종로구 청운효자동,공기식당,카레,4.48,561,673,서울 종로구 필운대로6길 20-1 1층,0507-1440-0930,서울특별시,종로구
...,...,...,...,...,...,...,...,...,...,...
14727,전북특별자치도 부안군 백산면,장수해장국,해장국,4.38,219,19,전북 부안군 부안읍 송정길 13 장수해장국,NaN,전북특별자치도,부안군
14728,전북특별자치도 부안군 백산면,최고다김밥 본점,김밥,4.41,199,11,전북 부안군 부안읍 봉신길 9,NaN,전북특별자치도,부안군
14729,전북특별자치도 부안군 백산면,롯데리아 부안점,햄버거,4.13,827,14,전북 부안군 부안읍 석정로 191,NaN,전북특별자치도,부안군
14730,전북특별자치도 부안군 백산면,형제골뼈다귀순대국,감자탕,4.27,1290,138,전북 부안군 부안읍 용암로 32,NaN,전북특별자치도,부안군
14731,전북특별자치도 부안군 상서면,개암곰탕,"곰탕,설렁탕",4.33,650,42,전북 부안군 상서면 부안로 1567,NaN,전북특별자치도,부안군

In [26]:
feat_df = df.groupby(['시도명','시군구'])[['평점','방문자 리뷰 수','블로그 리뷰 수']].mean().reset_index()
feat_df

         시도명  시군구        평점     방문자 리뷰 수    블로그 리뷰 수
0    강원특별자치도  강릉시  4.385164  1017.639344  262.049180
1    강원특별자치도  고성군  4.394643   559.571429  334.178571
2    강원특별자치도  동해시  4.363016   754.555556  182.142857
3    강원특별자치도  삼척시  4.280000   560.245614  128.736842
4    강원특별자치도  속초시  4.348367  1626.469388  790.836735
..       ...  ...       ...          ...         ...
221     충청북도  제천시  4.373043   934.669565  274.565217
222     충청북도  증평군  4.372727   948.909091   23.181818
223     충청북도  진천군  4.343409   532.522727   39.613636
224     충청북도  청주시  4.417287   891.251012   72.643725
225     충청북도  충주시  4.367285   468.152318   54.337748

[226 rows x 5 columns]

In [27]:
#feat_df.to_csv('시군구별_혼밥식당_평점.csv',index=False)